#!/usr/bin/env python3
"""Emit pack sources.yaml + retrieval-eval.yaml from structured JSON on stdin.

Input JSON:
  {
    "pack": "acme",
    "sources": [
      {"id": "my-app", "remote_url": "https://github.com/org/app.git",
       "default_branch": "main", "visibility": "private",
       "description": "...", "tags": ["app"]}
    ],
    "eval_questions": ["What is this product?", ...]   # optional
  }

Usage:
  python3 pack_yaml.py --out-dir profiles/acme < spec.json
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


def die(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(2)


def yaml_str(s: str) -> str:
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def emit_sources(sources: list[dict]) -> str:
    lines = [
        "# sources — generated by configure-pack.sh",
        "# After ./scripts/ingest.sh, mirrors land at",
        "#   /var/lib/code2wiki/data/mirrors/<id>",
        "sources:",
    ]
    for src in sources:
        sid = str(src.get("id") or "").strip()
        url = str(src.get("remote_url") or "").strip()
        if not sid or not ID_RE.match(sid):
            die(f"invalid source id: {sid!r}")
        if not url:
            die(f"missing remote_url for {sid}")
        branch = str(src.get("default_branch") or "main").strip() or "main"
        vis = str(src.get("visibility") or "private").strip() or "private"
        if vis not in ("private", "public"):
            die(f"visibility must be private|public for {sid}")
        desc = str(src.get("description") or f"Product source {sid}.").strip()
        tags = src.get("tags") or [sid]
        if isinstance(tags, str):
            tags = [tags]
        tag_s = ", ".join(str(t) for t in tags)
        lines += [
            f"  - id: {sid}",
            f"    remote_url: {url}",
            f"    # local_path: /var/lib/code2wiki/data/mirrors/{sid}",
            f"    default_branch: {branch}",
            # reconcile-sources.py historically read `branch`; keep both.
            f"    branch: {branch}",
            f"    visibility: {vis}",
            "    description: >",
            f"      {desc}",
            f"    tags: [{tag_s}]",
            "    include_globs:",
            "      - README.md",
            "      - docs/**",
            "      - \"**/*.md\"",
        ]
    lines.append("")
    return "\n".join(lines)


def emit_eval(pack: str, sources: list[dict], questions: list[str] | None) -> str:
    ids = [str(s["id"]) for s in sources]
    primary = ids[0] if ids else "example-docs"
    qs = questions or [
        f"What repositories does the {pack} appliance answer from?",
        f"Give a one-paragraph overview of {primary}.",
        f"How do I get started with {primary}?",
    ]
    lines = [
        "# retrieval-eval — generated by configure-pack.sh",
        "# Use expect_sources (not expect_source_ids).",
        "cases:",
    ]
    for i, q in enumerate(qs, start=1):
        expect = ids if len(ids) <= 2 else [primary]
        exp = ", ".join(expect)
        lines += [
            f"  - id: case-{i:02d}",
            f"    question: {yaml_str(q)}",
            f"    expect_sources: [{exp}]",
        ]
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", type=Path, required=True)
    ap.add_argument("--stdin-json", action="store_true", default=True)
    args = ap.parse_args()
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError as e:
        die(f"invalid JSON: {e}")
    pack = str(payload.get("pack") or "acme").strip()
    sources = payload.get("sources") or []
    if not isinstance(sources, list) or not sources:
        die("sources must be a non-empty list")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    sources_path = args.out_dir / "sources.yaml"
    eval_path = args.out_dir / "retrieval-eval.yaml"
    sources_path.write_text(emit_sources(sources), encoding="utf-8")
    eval_path.write_text(
        emit_eval(pack, sources, payload.get("eval_questions")),
        encoding="utf-8",
    )
    wiki = args.out_dir / "product-wiki.md"
    if not wiki.exists():
        wiki.write_text(
            f"# {pack} product notes\n\n"
            "Optional operator authority pages. Prefer capability ledger + corpus.\n",
            encoding="utf-8",
        )
    print(f"wrote {sources_path}")
    print(f"wrote {eval_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
