#!/usr/bin/env bash
# Ensure host FinClaw CLI is available (caller / setup agent).
#
# Usage:
#   ./scripts/ensure-finclaw.sh
#   ./scripts/ensure-finclaw.sh --skip          # require existing finclaw; never install
#   ./scripts/ensure-finclaw.sh --force-install # reinstall even if present
#
# Env:
#   FINCLAW_INSTALL_URL  default finogeeks/finclaw-cli install.sh raw URL
#   FINCLAW_INSTALL_DIR  forwarded to upstream installer
#   FINCLAW_VERSION      forwarded to upstream installer
set -euo pipefail

SKIP=0
FORCE=0
INSTALL_URL="${FINCLAW_INSTALL_URL:-https://raw.githubusercontent.com/finogeeks/finclaw-cli/main/install.sh}"

usage() {
  sed -n '2,14p' "$0" | sed 's/^# \{0,1\}//'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --skip|--skip-finclaw) SKIP=1; shift ;;
    --force-install) FORCE=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

# Discover finclaw on PATH or in common install dirs (persist hint for sibling scripts).
persist_path_hint() {
  local d="$1"
  [[ -n "$d" ]] || return 0
  if [[ -f docker-compose.yml ]]; then
    mkdir -p runtime
    cat >runtime/.finclaw-env <<EOF
# generated by ensure-finclaw.sh — source from site scripts
export PATH="${d}:\$PATH"
EOF
  fi
}

have_finclaw() {
  if command -v finclaw >/dev/null 2>&1; then
    return 0
  fi
  local d
  for d in "${FINCLAW_INSTALL_DIR:-$HOME/.local/bin}" "$HOME/.local/bin" /usr/local/bin; do
    if [[ -x "${d}/finclaw" ]]; then
      export PATH="${d}:$PATH"
      persist_path_hint "$d"
      return 0
    fi
  done
  return 1
}

print_version() {
  if have_finclaw; then
    finclaw --version 2>/dev/null || finclaw version 2>/dev/null || echo "finclaw (version unknown)"
  fi
}

if have_finclaw && [[ "$FORCE" != 1 ]]; then
  echo "ensure-finclaw: already available → $(command -v finclaw)"
  print_version | sed 's/^/  /' || true
  persist_path_hint "$(dirname "$(command -v finclaw)")"
  exit 0
fi

if [[ "$SKIP" == 1 ]]; then
  if have_finclaw; then
    echo "ensure-finclaw: --skip and finclaw present"
    exit 0
  fi
  echo "error: --skip-finclaw but 'finclaw' not on PATH" >&2
  echo "hint: install from https://github.com/finogeeks/finclaw-cli or omit --skip" >&2
  exit 1
fi

echo "ensure-finclaw: installing FinClaw CLI via ${INSTALL_URL}"
if ! command -v curl >/dev/null 2>&1; then
  echo "error: curl required to install FinClaw" >&2
  exit 1
fi

# Upstream installer places binary in FINCLAW_INSTALL_DIR (default ~/.local/bin).
curl -fsSL "$INSTALL_URL" | sh

if ! have_finclaw; then
  echo "error: finclaw still not on PATH after install" >&2
  echo "hint: export PATH=\"\$HOME/.local/bin:\$PATH\" and re-run" >&2
  exit 1
fi

echo "ensure-finclaw: ok → $(command -v finclaw)"
print_version | sed 's/^/  /' || true
persist_path_hint "$(dirname "$(command -v finclaw)")"